from rust:1.66.0

run ["cargo", "install", "wasm-pack"]
run ["rustup", "target", "add", "wasm32-unknown-unknown"]

workdir /workdir

# for webpack and deno
cmd wasm-pack build && wasm-pack build -t web -d pkg-web
