from rust:1.82.0

run ["cargo", "install", "wasm-pack"]
run ["rustup", "target", "add", "wasm32-unknown-unknown"]

workdir /workdir

# for webpack and deno
cmd ["bash", "-c", "wasm-pack build && wasm-pack build -t web -d pkg-web"]
